version: '3'

services:
  nsqd:
    image: nsqio/nsq:latest
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
      - "4152:4152"
    command: nsqd --broadcast-address=nsqd --max-heartbeat-interval=6m0s --msg-timeout=6m0s --lookupd-tcp-address=nsqlookupd:4160 --data-path=/data
    volumes:
      - /data
    restart: always

  nsqlookupd:
    image: nsqio/nsq:latest
    ports:
      - "4161:4161"
      - "4160:4160"
    command: nsqlookupd -broadcast-address=nsqlookupd
    restart: always

  nsqadmin:
    depends_on:
      - nsqlookupd
    image: nsqio/nsq:latest
    ports:
      - "4171:4171"
    command: nsqadmin --lookupd-http-address=nsqlookupd:4161
    restart: always
